# Generated by Django 5.1.4 on 2025-01-16 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_message_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='client',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='event_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientmsg',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='guest_messages/'),
        ),
    ]
