# Generated by Django 5.1.4 on 2025-01-16 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_delete_message_delete_post_client_event_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client_name',
            new_name='event_name',
        ),
    ]
