# Generated by Django 5.1.4 on 2025-01-19 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_rename_client_name_client_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='theme_settings',
            field=models.JSONField(default=dict),
        ),
    ]
