# Generated by Django 5.1.4 on 2025-01-20 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_theme_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='event_logo',
            field=models.ImageField(blank=True, null=True, upload_to='event_logos/'),
        ),
    ]
