# Generated by Django 5.1.4 on 2025-01-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_client_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_url',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
